const fs = require('fs');
const path = require('path');
const { get, run, all } = require('./db');

const csvPath = path.join(__dirname, 'cmms_maintenance_10000.csv');

if (!fs.existsSync(csvPath)) {
  console.error("CSV file not found. Please run 'python generate_dataset.py' first.");
  process.exit(1);
}

console.log("Reading CSV file...");
const csvData = fs.readFileSync(csvPath, 'utf8');
const lines = csvData.trim().split('\n');

if (lines.length < 2) {
  console.error("CSV file is empty or invalid.");
  process.exit(1);
}

console.log("Clearing existing maintenance logs...");
run('DELETE FROM maintenance_logs');

// Get all current machines so we can map names like "M001" to actual database IDs
const machineMap = new Map();
const currentMachines = all('SELECT id, name FROM machines');
currentMachines.forEach(m => machineMap.set(m.name, m.id));

let insertCount = 0;

console.log("Importing data... This might take a few seconds.");

// Using a transaction drastically improves bulk insert speed in SQLite
run('BEGIN TRANSACTION');

try {
  for (let i = 1; i < lines.length; i++) {
    const parts = lines[i].split(',');
    if (parts.length < 4) continue;
    
    const mName = parts[0];
    const repair_time = parseFloat(parts[1]);
    const failure_time = parseFloat(parts[2]);
    const created_at = parts[3];

    let mId = machineMap.get(mName);
    
    // If the machine generated by the script doesn't exist in our DB, create it!
    if (!mId) {
      const res = run(
        `INSERT INTO machines (name, status, working_hours, idle_hours, last_service_date, next_service_date)
         VALUES (?, ?, ?, ?, ?, ?)`,
        [mName, 'Active', 0, 0, null, null]
      );
      mId = res.lastInsertRowid;
      machineMap.set(mName, mId);
    }

    run(
      `INSERT INTO maintenance_logs (machine_id, repair_time, failure_time, created_at)
       VALUES (?, ?, ?, ?)`,
      [mId, repair_time, failure_time, created_at]
    );
    insertCount++;
  }
  
  run('COMMIT');
  console.log(`Successfully imported ${insertCount} records!`);
  console.log(`Created ${machineMap.size - currentMachines.length} new machines.`);
} catch (error) {
  run('ROLLBACK');
  console.error("An error occurred during import:", error);
}
